version: "3.8"
services:
  api:
    container_name: api-container
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/server
    ports:
      - "3000:3000"
    networks:
      - backend
networks: 
  backend:
    name: backend